### ISSUE TITLE
 CB Configuration Baseline Compliance by Configuration Item with Values error due to missing database function

### ISSUE THREAD

**Issue by EvilGrinUK** [JhonnyTerminus/SCCMZone#10]
Hi,

This report fails to run in my enviroment due to the fact that the function 'fn_rbac_ListCIRules' is not present in my SCCM site Database. (Server 2016, SQL 2016, SCCM Current Branch v1806).

Thanks.

**Comment by Ioan-Popovici** [comment]
Hi, strangely some of the reporting functions seem to arbitrarily get removed or added with each version.
Change the report query to dbo.fn_ListCIRules, I will update the report in a few minutes

Thanks for reporting this
