### ISSUE TITLE
BitLocker

### ISSUE THREAD

**Issue by ChandraMaroutu** [JhonnyTerminus/SCCMZone#15]
Thank you for providing a wonder full script to get the Bitlocker status.
Could you please share the script if have any where it checks and enables all the drives in the computer, whether it is OS Drive or Fixed drive, excluding CDDrive, External HDD and USB drives. And then save the recovery key to AD

**Comment by Ioan-Popovici** [comment]
I'm sorry I don't do these kinds of requests
