### ISSUE TITLE
SQL 2016 not in the reports

### ISSUE THREAD

**Issue by knlsystemhostingdk** [JhonnyTerminus/SCCMZone#2]
Github it is then :) 

Ok, the HW collection should now have run.. but i still dont see SQL2016, i replaced all MOF and RDL files from the download page.. 

Any ideas ? 

/Kenneth

**Comment by JhonnyTerminus** [comment]
Great this is much better.

Can you pleas check the following:
* Check if you receive the Hardware Inventory from the SQL 2016
* Check if there are any entries in the SQL CM DB tables
* Check one of the SQL servers to see if the WMI entries are present

I will look on my side one more time to see if everything is OK.
Got to deploy/find a SQL 2016 server to test

**Comment by knlsystemhostingdk** [comment]
No sql 2016 data in the database, so its not getting collected.... I know i have 2016 sqls there, i saw them in an earlier version :) 
So where do i look ? the inbox mof or the sqlclasses mof ? 
/Kenneth

**Comment by JhonnyTerminus** [comment]
This points to an error in the HW collection. 
You could also try to reboot the site server or restart the site. My HW got stuck once when modifying configuration.mof.
* Check the InventoryAgent.log for errors
* Check the last hwi collection on the 2016 SQL machine(s), you can use resource explorer for that, no need to log on on the machine
Here is some hwi troubleshooting how-to:
https://www.enhansoft.com/blog/troubleshooting-inventory-flow

**Comment by JhonnyTerminus** [comment]
Can't reproduce, the 2016 versions shows up in the new environment I tested.
So it must be some problem with the HWI collection.
![ss](https://user-images.githubusercontent.com/17069425/35564369-35abc618-05ba-11e8-8826-9106d6888d40.jpg)

**Comment by knlsystemhostingdk** [comment]
YAY :) 
Got, I reimported all mof files and rebooted the site server. and now it all looks good :) 

Thanks for the help :)

**Comment by JhonnyTerminus** [comment]
That’s great news! 
Glad you figured it out :)
