### ISSUE TITLE
Cleaning the SCCM Cache the right way with PowerShell

### ISSUE THREAD

**Issue by mancitymike** [JhonnyTerminus/SCCMZone#3]
Hi loan

I hope this is the correct way to raise a query about your powershell script?

Is there a way to remove ALL non persistent data from the cache folder ? 

If I run the script without parameters I do get folders deleted but I seem to get a lot of folders left over - some are persistent but most other folders have time stamps going back 3 months or more

many thanks
Mike

**Comment by JhonnyTerminus** [comment]
Hi, 
Sorry for the late reply I was on vacation. Yes this is perfect, Medium is not the right 'Medium' for raising issues :)

All non-persistent content should be deleted. Maybe there is a bug somewhere in the code.

Watch out for these parameters:
.PARAMETER LowDiskSpaceThreshold
    Specifies the low disk space threshold percentage after which the cache is cleaned. Default is: '100'.
    If it's set to '100' Free Space Threshold Percentage is ignored.
.PARAMETER ReferencedThreshold
    Specifies to remove cache element only if it has not been referenced in specified number of days. Default is: 0.
    If it's set to '0' Last Referenced Time is ignored.

Please run the following functions standalone, after you run the script without parameters and get back to me with the results.

Get-CCMCachedApplications
Get-CCMCachedPackages
Get-CCMCachedUpdates

We should be able to see if there is something off with the removal logic.

Ioan

**Comment by JhonnyTerminus** [comment]
>Hi loan ...

@mancitymike is this still an issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JhonnyTerminus** [comment]
Should be fixed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
