### ISSUE TITLE
CB Configuration Baseline Compliance by Configuration Item with Values error

### ISSUE THREAD

**Issue by JhonnyTerminus** [JhonnyTerminus/SCCMZone#5]
Hi, thanks for the report. Report runs but it does it has problem as below.

![image](https://user-images.githubusercontent.com/42178699/43779505-38017796-9a61-11e8-9204-52ae739e690f.png)

**Comment by JhonnyTerminus** [comment]
I've uploaded a new report because the one I gave you had a company field that might cause you problems [here](https://raw.githubusercontent.com/JhonnyTerminus/SCCMZone/master/Reporting/Compliance/CB%20Configuration%20Baseline%20Compliance%20by%20Configuration%20Item%20with%20Values.rdl)

The thing is that the function that throws an error should exist in your database see screenshoot:
![image](https://user-images.githubusercontent.com/17069425/43784155-bad0562c-9a63-11e8-9eab-e943bf5075ff.png)

**Comment by serkanuzuner** [comment]
Thanks, can you send me this function text for creating this because i dont have this on reporting db

**Comment by JhonnyTerminus** [comment]
You should have it. What version of SCCM are you running?

``
USE [CM_YOURSITECODE]
GO
/****** Object:  UserDefinedFunction [dbo].[fn_rbac_CICurrentSettingsComplianceStatusDetail]    Script Date: 2018-08-08 11:01:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- 
-- Name         : fn_rbac_CICurrentSettingsComplianceStatusDetail 
-- Definition   : SqlObjs 
-- Scope        : CAS_OR_PRIMARY 
-- Object       : IF 
-- Dependencies : <Detect> 
-- Description  : RBAC-controlled access to view v_CICurrentSettingsComplianceStatusDetail 
-- 
Create FUNCTION [dbo].[fn_rbac_CICurrentSettingsComplianceStatusDetail] (@UserSIDs nvarchar(max)) 
    RETURNS TABLE 
AS 
RETURN 
( 
  SELECT 
    * 
  FROM v_CICurrentSettingsComplianceStatusDetail 
)

**Comment by serkanuzuner** [comment]
Hi,

yes it is located under CM_DB but does not located on reporting database, and above command suceeded but didnt created fn under reporting db




![image](https://user-images.githubusercontent.com/42178699/43832035-c20ddf9e-9b0e-11e8-980a-a06265d934ec.png)

**Comment by JhonnyTerminus** [comment]
So the reporting service Database is located on a different server?

If the reporting services and SCCM DB share the same server this should not be a problem.

You need to be able to query the SCCM database for this report to work.

**Comment by JhonnyTerminus** [comment]
>Thanks, can you send me this function text for creating this because i dont have this on reporting db

@serkanuzuner dod you manage to figure this out?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JeroenBudding** [comment]
Jhonny,

I have the same error message when I try to configure the following report.

![error_dbo fn_rbac_cicurrentsettingscompliancestatusdetail](https://user-images.githubusercontent.com/42830258/44861244-6c6dfa80-ac78-11e8-92d6-379cdc472a92.jpg)

**Comment by JhonnyTerminus** [comment]
Should be fixed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
